### PR TITLE
Added template argument deduction support to toJsonValue

### PR DESCRIPTION
**Pull request by vtnerd**

### CODE REVIEW

**Comment by tewinget** [comment]
I'll test this later, but I have no doubt it works.  I tried doing it this
way, but must have screwed something up.  Thanks!

**Comment by tewinget** [comment]
Although with the talk about using cereal for other things I'm considering
moving in that direction.  Still not sure how I feel about it, will have to
do more research.

**Comment by vtnerd** [comment]
I was just looking at that pull request, and was going to bring your attention to it. Internally Cereal uses rapidjson and creates a DOM before reading or writing JSON. So it should be similar in behavior and performance to your code. And my suggestion to remove the DOM creation entirely from the output side would still be possible, but would require a custom output format. Its not as difficult as it sounds.

The unfortunate part with Cereal is that everything needs to be in the same compilation unit as the input/output archive object. Lots of header creep.

**Comment by vtnerd** [comment]
Oh I take that last part back! It does not have to be in the same header. Its just that you to explicitly instantiate each function against each archive format used.

**Comment by tewinget** [comment]
Yeah, I would prefer to keep serialization separate from the objects being
serialized, other than those whose sole purpose is message passing.

**Comment by vtnerd** [comment]
The two concepts are still separate ... maybe I am misunderstanding you. To clarify what I meant:

```c++
namespace cryptonote {
template<typename T>
void serialize(T& archive, some_message& message)
{
  ...
}
```
still allows external functions for input/output. Its just that the archive type is type polymorphic.

**Comment by tewinget** [comment]
I think I misunderstood your other comment.  At any rate, I have research
to do.

**Pull request merged**
